import random
import pandas as pd
import numpy as np

def __create_individuals__(tract):
    """
    Generate a population of individuals based on age and sex distribution data from a census tract.

    Parameters:
    - tract: Census tract data containing age and sex distribution information.

    Returns:
    - DataFrame: Population of individuals with columns for age, gender, and unique identifier.
    """
    #print("- Step 1.1 Create People -")
    # age_sex_groups = (tract[4:45].drop('DP0010039')).astype(int)
    age_sex_groups = (tract[13:50]).drop(['DP1_0049C']).astype(int)
    # print(len(age_sex_groups))

    # dfs=pd.DataFrame()
    individual_dfs = []

    # code is the index(generated by the enumerate build-in function) of the list
    # ,which indicates the age and sex group
    # code 0~17 male, 18~35 female
    for code, count in enumerate(age_sex_groups):  # enumerate is to create the index for the list
        # print(code, count)
        base_age = (code % 18) * 5
        gender = 'm' if code < 18 else 'f'
        ages = []
        for offset in range(4):
            ages.extend([offset + base_age] * (count // 5))
        ages.extend([base_age + 4] * (count - len(ages)))  # todo match the age distribution of age in the future

        # temp = pd.DataFrame({'code':code, 'age':ages,'gender':[gender]*count})
        individual_dfs.append(pd.DataFrame({'code': code, 'age': ages, 'gender': [gender] * count}))

    df = pd.concat(individual_dfs).sample(frac=1, random_state=123).reset_index(drop=True)
    # df = pd.concat([dfs]).sample(frac=1,random_state=123).reset_index(drop=True)
    df.index = tract.name + 'i' + df.index.to_series().astype(str)

    return df

    # if tract.DP1_0001C == len(df) and tract.DP1_0025C == len(df[df.gender == 'm']) and tract.DP1_0049C == len(
    #         df[df.gender == 'f']):
    #     # print(f"{tract.name} total population match: "
    #     #       f"{tract.DP1_0001C} = generated {len(df)}")
    #     # print(f"{tract.name} total male population match: "
    #     #       f"{tract.DP1_0025C} = generated {len(df[df.gender == 'm'])}")
    #     # print(f"{tract.name} total female population match: "
    #     #       f"{tract.DP1_0049C} = generated {len(df[df.gender == 'f'])}")
    #
    #     return df
    # else:
    #     print(f"{tract.name} has an issue")